### ISSUE TITLE
issue with data download from earthscope

### ISSUE THREAD

**Issue by kmaterna** [kmaterna/Mendocino_Geodesy#6]
The urls from the GNSS script ("https://data.unavco.org/...") directs to the same page as the gage url ("https://gage-data.earthscope.org/...") but wget breaks down when it tries to go into individual folders. 

So, the only thing "get_earthscope_data.sh" is able to download with the current URLs is an index.html file since it can't move down the directories without links breaking. This took a surprisingly long time to figure out, since the displayed webpages are identical! I think this happened with the whole Earthscope merger thing.

**Comment by web-sys1** [comment]
Steps to reproduce:

1. Open Ubuntu and type `sudo apt update`
2. [Download and Install Conda on Linux (Ubuntu)](https://linux.how2shout.com/install-miniconda-on-ubuntu-22-04-lts-jammy-linux/).
3. Run _sudo wget -c https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh_
4. Follow these steps, then use `$ sudo chmod +x Miniconda3-latest-Linux-x86_64.sh`
5. Clone [repository ](https://github.com/kmaterna/GNSS_TimeSeries_Viewers.git) (right click on link and select copy) into desired directory. It can be done with `git clone https://github.com/kmaterna/GNSS_TimeSeries_Viewers.git`
6.  Type `cd GNSS_TimeSeries_Viewers/`, and run `conda env create` or `conda env update` `-f requirements.yaml -n gnss`
7. Having installed packages:  `earthscope-cli` and `earthscope-sdk`. Use `pip3 install earthscope-cli Tectonic-Utils` to install these packages. Now, you can switch conda environment by using `conda activate gnss`.
8. Login into Earthscope Consortium. If you don't have one, sign up to create one.
9. Use `es sso login` to link your account SSO authorization page in your default browser in order to proceed.
10. In `GNSS_TimeSeries_Viewers` directory, run `bash ./gnss_timeseries_viewers/getting_gnss_data/update_data_holdings.sh`.

After running `es sso`, It ran into error:

```
Traceback (most recent call last):
  File "/home/scm/miniconda3/envs/gnss/bin/es", line 5, in <module>
    from earthscope_cli.main import app
  File "/home/scm/miniconda3/envs/gnss/lib/python3.12/site-packages/earthscope_cli/main.py", line 3, in <module>
    from earthscope_cli import m2m, sso, user
  File "/home/scm/miniconda3/envs/gnss/lib/python3.12/site-packages/earthscope_cli/user.py", line 7, in <module>
    from earthscope_sdk.user.user import get_user, lookup_anon
ImportError: cannot import name 'lookup_anon' from 'earthscope_sdk.user.user' (/home/scm/miniconda3/envs/gnss/lib/python3.12/site-packages/earthscope_sdk/user/user.py)

```
It seems to be problem with package of `earthscope-cli`, so I used:

``` sh
$ sudo vi /home/scm/miniconda3/envs/gnss/lib/python3.12/site-packages/earthscope_cli/user.py
```
I looked into file:

``` python
from typing import List
import typer

from rich import print
from earthscope_cli.m2m import CliClientCredentialsFlow
from earthscope_cli.sso import device_flow
from earthscope_sdk.user.user import get_user, lookup_anon

app = typer.Typer()

@app.command()
def get():
    device_flow.load_tokens()
    user = get_user(device_flow.access_token)
    print(user)

```

It seems that `lookup_anon` function was non-existent in package. So i decided to remove it from `../lib/python3.12/site-packages/earthscope_cli/user.py` file.

Code seems to work again.

```
$ es sso -h
```
```
 Usage: es sso [OPTIONS] COMMAND [ARGS]...

 Login to Earthscope API using SSO with your user account


╭─ Options ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --help          Show this message and exit.                                                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ Commands ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ access         Print the access token body (or token). Automatically refreshes the token when necessary                                                              │
│ expires        Print the date & time at which the access token expires                                                                                               │
│ id             Print the ID token body (or token)                                                                                                                    │
│ issued         Print the date & time at which the access token was issued                                                                                            │
│ login          Login to Earthscope API using SSO with your user account                                                                                              │
│ logout         Clear your local SSO tokens                                                                                                                           │
│ refresh        Refresh your SSO session, revoke your refresh token, or print out the refresh token                                                                   │
│ scope          Print the access token's scope                                                                                                                        │
│ state          Print all SSO state information stored locally on this machine                                                                                        │
│ ttl            Print the access token's time-to-live (TTL)                                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by web-sys1** [comment]
After an hour and a half, I took a stand, and ran `bash ./gnss_timeseries_viewers/getting_gnss_data/get_earthscope_data.sh` in **`GNSS_TimeSeries_Viewers`** directory.

However, I got stuck in the problem.

```
--2023-11-27 12:38:40--  https://data.unavco.org/archive/gnss/products/position/
Resolving data.unavco.org (data.unavco.org)... 18.165.171.92, 18.165.171.43, 18.165.171.48, ...
Connecting to data.unavco.org (data.unavco.org)|18.165.171.92|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 770579 (753K) [text/html]
Saving to: ‘index.html.tmp’

index.html.tmp                            100%[=====================================================================================>] 752.52K  1.44MB/s    in 0.5s

Last-modified header missing -- time-stamps turned off.
2023-11-27 12:38:43 (1.44 MB/s) - ‘index.html.tmp’ saved [770579/770579]

Removing index.html.tmp since it should be rejected.

FINISHED --2023-11-27 12:38:43--
Total wall clock time: 2.9s
Downloaded: 1 files, 753K in 0.5s (1.44 MB/s)
--2023-11-27 12:38:43--  https://data.unavco.org/archive/gnss/products/event/
Resolving data.unavco.org (data.unavco.org)... 18.165.171.92, 18.165.171.43, 18.165.171.48, ...
Connecting to data.unavco.org (data.unavco.org)|18.165.171.92|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 213664 (209K) [text/html]
Saving to: ‘index.html.tmp’

index.html.tmp                            100%[=====================================================================================>] 208.66K   655KB/s    in 0.3s

2023-11-27 12:38:44 (655 KB/s) - ‘index.html.tmp’ saved [213664/213664]

Removing index.html.tmp since it should be rejected.

FINISHED --2023-11-27 12:38:44--
Total wall clock time: 1.0s
Downloaded: 1 files, 209K in 0.3s (655 KB/s)
cp: cannot stat 'data.unavco.org/archive/gnss/products/event/*.evt': No such file or directory
rm: cannot remove 'data.unavco.org': No such file or directory
--2023-11-27 12:38:45--  https://data.unavco.org/archive/gnss/products/offset/cwu.kalts_nam14.off
Resolving data.unavco.org (data.unavco.org)... 18.165.171.92, 18.165.171.43, 18.165.171.48, ...
Connecting to data.unavco.org (data.unavco.org)|18.165.171.92|:443... connected.
HTTP request sent, awaiting response... 304 Not Modified
File ‘cwu.kalts_nam14.off’ not modified on server. Omitting download.

--2023-11-27 12:38:46--  https://data.unavco.org/archive/gnss/products/velocity/
Resolving data.unavco.org (data.unavco.org)... 18.165.171.92, 18.165.171.43, 18.165.171.48, ...
Connecting to data.unavco.org (data.unavco.org)|18.165.171.92|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 25010 (24K) [text/html]
Saving to: ‘index.html.tmp’

index.html.tmp                            100%[=====================================================================================>]  24.42K  --.-KB/s    in 0.08s

Last-modified header missing -- time-stamps turned off.
2023-11-27 12:38:46 (302 KB/s) - ‘index.html.tmp’ saved [25010/25010]

Removing index.html.tmp since it should be rejected.

FINISHED --2023-11-27 12:38:46--
Total wall clock time: 0.7s
Downloaded: 1 files, 24K in 0.08s (302 KB/s)

```
what something else could be made to fix the irregularities?

**Comment by web-sys1** [comment]
HI @kmaterna

For more details, please visit page [here](https://www.unavco.org/data/gps-gnss/file-server/file-server-access-examples.html)

**Comment by kmaterna** [comment]
@web-sys1  wow, thank you for one of the most detailed bug reports I've ever gotten, and for the nudge to fix this issue.  I have an idea that the second issue is related to a wrong URL redirection, but I'll get a chance to test the fix in the next two days.  This new-ish data download system has been a bit painful... thank you so much for reporting it!

**Comment by web-sys1** [comment]
@kmaterna 

You should look carefully at the wget output. So i used `--debug` flag to see what happens with file fetch.

`wget -N -r -np -erobots=off --accept="*.cwu.final_nam14.pos,*.cwu.final_igs14.pos" --reject="tmp,index.html.tmp*" --level=2 --debug --verbose --header "authorization: Bearer $(es sso access --token)" https://data.unavco.org/archive/gnss/products/position/`

```
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/cwu.ant14.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/cwu.ant14.pos.tar.gz (cwu.ant14.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/cwu.fanet_ant14.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/cwu.fanet_ant14.pos.tar.gz (cwu.fanet_ant14.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/cwu.fanet_igs14.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/cwu.fanet_igs14.pos.tar.gz (cwu.fanet_igs14.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/cwu.final_igs08.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/cwu.final_igs08.pos.tar.gz (cwu.final_igs08.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/cwu.final_igs14.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/cwu.final_igs14.pos.tar.gz (cwu.final_igs14.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/cwu.final_nam08.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/cwu.final_nam08.pos.tar.gz (cwu.final_nam08.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/cwu.final_nam14.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/cwu.final_nam14.pos.tar.gz (cwu.final_nam14.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/cwu.igs08.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/cwu.igs08.pos.tar.gz (cwu.igs08.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/cwu.igs14.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/cwu.igs14.pos.tar.gz (cwu.igs14.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/cwu.nam08.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/cwu.nam08.pos.tar.gz (cwu.nam08.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/cwu.nam14.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/cwu.nam14.pos.tar.gz (cwu.nam14.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/cwu.rapid_igs08.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/cwu.rapid_igs08.pos.tar.gz (cwu.rapid_igs08.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/cwu.rapid_igs14.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/cwu.rapid_igs14.pos.tar.gz (cwu.rapid_igs14.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/cwu.rapid_nam08.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/cwu.rapid_nam08.pos.tar.gz (cwu.rapid_nam08.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/cwu.rapid_nam14.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/cwu.rapid_nam14.pos.tar.gz (cwu.rapid_nam14.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/gage_gps.igs08.txt".
https://gage-data.earthscope.org/archive/gnss/products/position/gage_gps.igs08.txt (gage_gps.igs08.txt) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/gage_gps.igs14.txt".
https://gage-data.earthscope.org/archive/gnss/products/position/gage_gps.igs14.txt (gage_gps.igs14.txt) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/gage_gps.nam08.txt".
https://gage-data.earthscope.org/archive/gnss/products/position/gage_gps.nam08.txt (gage_gps.nam08.txt) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/gage_gps.nam14.txt".
https://gage-data.earthscope.org/archive/gnss/products/position/gage_gps.nam14.txt (gage_gps.nam14.txt) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/nmt.ant14.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/nmt.ant14.pos.tar.gz (nmt.ant14.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/nmt.fanet_ant14.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/nmt.fanet_ant14.pos.tar.gz (nmt.fanet_ant14.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/nmt.fanet_igs14.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/nmt.fanet_igs14.pos.tar.gz (nmt.fanet_igs14.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/nmt.final_igs08.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/nmt.final_igs08.pos.tar.gz (nmt.final_igs08.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/nmt.final_igs14.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/nmt.final_igs14.pos.tar.gz (nmt.final_igs14.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/nmt.final_nam08.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/nmt.final_nam08.pos.tar.gz (nmt.final_nam08.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/nmt.final_nam14.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/nmt.final_nam14.pos.tar.gz (nmt.final_nam14.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/nmt.igs08.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/nmt.igs08.pos.tar.gz (nmt.igs08.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/nmt.igs14.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/nmt.igs14.pos.tar.gz (nmt.igs14.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/nmt.nam08.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/nmt.nam08.pos.tar.gz (nmt.nam08.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/nmt.nam14.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/nmt.nam14.pos.tar.gz (nmt.nam14.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/pbo.ant14.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/pbo.ant14.pos.tar.gz (pbo.ant14.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/pbo.fanet_ant14.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/pbo.fanet_ant14.pos.tar.gz (pbo.fanet_ant14.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/pbo.fanet_igs14.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/pbo.fanet_igs14.pos.tar.gz (pbo.fanet_igs14.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/pbo.final_igs08.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/pbo.final_igs08.pos.tar.gz (pbo.final_igs08.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/pbo.final_igs14.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/pbo.final_igs14.pos.tar.gz (pbo.final_igs14.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/pbo.final_nam08.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/pbo.final_nam08.pos.tar.gz (pbo.final_nam08.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/pbo.final_nam14.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/pbo.final_nam14.pos.tar.gz (pbo.final_nam14.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/pbo.igs08.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/pbo.igs08.pos.tar.gz (pbo.igs08.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/pbo.igs14.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/pbo.igs14.pos.tar.gz (pbo.igs14.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/pbo.nam08.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/pbo.nam08.pos.tar.gz (pbo.nam08.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Deciding whether to enqueue "https://gage-data.earthscope.org/archive/gnss/products/position/pbo.nam14.pos.tar.gz".
https://gage-data.earthscope.org/archive/gnss/products/position/pbo.nam14.pos.tar.gz (pbo.nam14.pos.tar.gz) does not match acc/rej rules.
Decided NOT to load it.
Removing file due to recursive rejection criteria in recursive_retrieve():
Removing data.unavco.org/archive/gnss/products/position/index.html.tmp since it should be rejected.

FINISHED --2023-11-28 09:42:36--
Total wall clock time: 5.2s
Downloaded: 1 files, 753K in 0.8s (982 KB/s)
Saving HSTS entries to /home/scm/.wget-hsts
```

**Comment by kmaterna** [comment]
Fixed (at least on my machine) with the URL suggestion given in the following commit:
[b437767](https://github.com/kmaterna/GNSS_TimeSeries_Viewers/commit/b437767fe3b8681358834ebe08244af3d1de4f87)
